[package]
name = "shared"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Shared resources and configuration for OSC Clock"

[lib]
name = "shared"
path = "src/lib.rs"

[dependencies]
once_cell = { workspace = true }
chrono = { workspace = true }
