[package]
name = "osc_clock"
version.workspace = true
edition.workspace = true
authors.workspace = true

description = "Send date and time to VRChat via OSC"

[lib]
name = "osc_clock"
path = "src/lib.rs"

# CLI binary (can run standalone)
[[bin]]
name = "osc_clock"
path = "src/bin/main.rs"

[build-dependencies]
build-utils = { path = "../build-utils" }

[dependencies]
vrchat_osc = { workspace = true }
tokio = { workspace = true }
rosc = { workspace = true }
once_cell = { workspace = true }
fake = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
rust-i18n = { workspace = true }
bitflags = { workspace = true }
clap = { workspace = true }
shared = { path = "../shared" }
