[package]
name = "osc_clock"
version.workspace = true
edition.workspace = true
authors.workspace = true

description = "Send date and time to VRChat via OSC"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "osc_clock"
path = "src/lib.rs"

[[bin]]
name = "osc_clock"
path = "src/bin/main.rs"

[dependencies]
vrchat_osc = { workspace = true }
tokio = { workspace = true }
rosc = { workspace = true }
once_cell = { workspace = true }
fake = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
rust-i18n = { workspace = true }
bitflags = { workspace = true }
clap = { workspace = true }